
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mjed
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        add_emp = new javax.swing.JButton();
        add_dep = new javax.swing.JButton();
        add_product = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        showCustomer = new javax.swing.JButton();
        showEmp = new javax.swing.JButton();
        showOrder = new javax.swing.JButton();
        showDep = new javax.swing.JButton();
        showProd = new javax.swing.JButton();
        add_cus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMS");
        setResizable(false);

        jLabel1.setText("Add new:");

        add_emp.setText("Employee");
        add_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_empActionPerformed(evt);
            }
        });

        add_dep.setText("Dependant");
        add_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_depActionPerformed(evt);
            }
        });

        add_product.setText("Product");
        add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_productActionPerformed(evt);
            }
        });

        jLabel2.setText("Show all and delete and edit:");

        showCustomer.setText("Customer");
        showCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCustomerActionPerformed(evt);
            }
        });

        showEmp.setText("Employee");
        showEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEmpActionPerformed(evt);
            }
        });

        showOrder.setText("Order");
        showOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOrderActionPerformed(evt);
            }
        });

        showDep.setText("Dependent");
        showDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDepActionPerformed(evt);
            }
        });

        showProd.setText("Product");
        showProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showProdActionPerformed(evt);
            }
        });

        add_cus.setText("Customer");
        add_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Inventroy Manegment System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(add_product, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(add_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(add_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(add_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 56, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(showOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(showCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showDep, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                            .addComponent(showProd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_emp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_product))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_cus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_dep)))
                .addGap(43, 43, 43)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showEmp)
                    .addComponent(showDep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showOrder)
                    .addComponent(showCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_empActionPerformed
        // TODO add your handling code here:
        // add emp
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add_emp emp = new Add_emp();
                emp.setConnection(con);
                emp.setVisible(true);
            }
        });
    }//GEN-LAST:event_add_empActionPerformed

    private void add_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_depActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add_dependant dep = new Add_dependant();
                dep.setConnection(con);
                dep.setVisible(true);
            }
        });
    }//GEN-LAST:event_add_depActionPerformed

    private void add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_productActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add_Products product = new Add_Products();
                product.setConnection(con);
                product.setVisible(true);
            }
        });
    }//GEN-LAST:event_add_productActionPerformed

    private void showCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCustomerActionPerformed
        // TODO add your handling code here:
        showTabel("Customers");

    }//GEN-LAST:event_showCustomerActionPerformed

    private void showEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEmpActionPerformed
        // TODO add your handling code here:
        showTabel("Employees");
    }//GEN-LAST:event_showEmpActionPerformed

    private void showOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOrderActionPerformed
        // TODO add your handling code here:
        showTabel("Orders");

    }//GEN-LAST:event_showOrderActionPerformed

    private void showDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDepActionPerformed
        // TODO add your handling code here:
        showTabel("Dependents");
    }//GEN-LAST:event_showDepActionPerformed

    private void showProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showProdActionPerformed
        // TODO add your handling code here:
        showTabel("Products");

    }//GEN-LAST:event_showProdActionPerformed

    private void add_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cusActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add_Customer customer = new Add_Customer();
                customer.setConnection(con);
                customer.setVisible(true);
            }
        });
    }//GEN-LAST:event_add_cusActionPerformed

    /**
     * @param args the command line arguments
     */
    private void showTabel(String tabel) {

        String querue = "SELECT * FROM ";
        switch (tabel) {
            case "Employees":
                querue += "EMPLOYEE";
                break;
            case "Dependents":
                querue += "Dependent";
                System.out.println(querue);
                break;
            case "Customers":
                querue += "CUSTOMER";
                break;
            case "Products":
                querue += "PRODUCT";
                break;
            case "Orders":
                querue += "ORD";
                break;
        }
        try {
            Statement st = con.prepareStatement(querue);
            ResultSet rs = st.executeQuery(querue);
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    tableView tv = new tableView();
                    tv.setConnection(con);
                    tv.getTable().setModel(DbUtils.resultSetToTableModel(rs));
                    tv.setMainLabel(tabel);
                    switch (tabel) {
                        case "Employees":
                            tv.getLabell().setText("EmployeeID: ");
                            tv.updateButton(true);
                            break;
                        case "Dependents":
                            tv.getLabell().setText("EmployeeID: ");
                            tv.getLabel2().setText("Dependent Phone: ");
                            tv.getLabel2().setVisible(true);
                            tv.getInput2().setVisible(true);
                            tv.updateButton(false);
                            break;
                            
                        case "Customers":
                            tv.getLabell().setText("Customer Phone: ");
                            tv.updateButton(true);

                            break;
                        case "Products":
                            tv.getLabell().setText("Product ID: ");
                            tv.updateButton(true);
                            break;
                        case "Orders":
                            tv.getLabell().setText("Order number: ");
                            tv.OrderView();
                            tv.updateButton(false);
                            break;
                    }
                    tv.setVisible(true);
                }
            });

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);;
            }
        });
    }
    Connection con;

    public void setConnection(Connection con) {
        this.con = con;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_cus;
    private javax.swing.JButton add_dep;
    private javax.swing.JButton add_emp;
    private javax.swing.JButton add_product;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton showCustomer;
    private javax.swing.JButton showDep;
    private javax.swing.JButton showEmp;
    private javax.swing.JButton showOrder;
    private javax.swing.JButton showProd;
    // End of variables declaration//GEN-END:variables
}
